version: 1.2.4

cache: false

registration:
  socialLogins:
    - "openid"

mcpServers:
  directus:
    url: https://directus-production-e5ad.up.railway.app/mcp
    type: sse
    headers:
      Authorization: "Bearer ${DIRECTUS_TOKEN}"
    